database-mesh/pisanix

pisa-controller/pkg/kubernetes/client.go
1.  FIX nil pointer err for get kubernetes client
=> Fix nil pointer err for get kubernetes client

pisa-proxy/Cargo.lock, pisa-proxy/Cargo.toml
Close #31 
Only those authorized to database-mesh/lrpar can clone project by `ssh`. Using `https` instead of `ssh` when cloning lrpar.
=> Fix cargo build failed caused by no authentication

.github/workflows/go.yml, pisa-controller/pkg/kubernetes/types.go, pisa-controller/pkg/proxy/config.go, pisa-controller/pkg/proxy/types.go, pisa-proxy/examples/example-config.toml, pisa-proxy/proxy/src/proxy.rs
- unified configs bewteen controll and proxy: rename username to user,  change type of port from string to uint32
- add golang build with subdirectory `pisa-controller`
- add default host `127.0.0.1` and port `3306` to default mysql node endpoint
=> refactor(configs): unified configs bewteen controller and proxy

pisa-proxy/plugin/src/config.rs
- fix serde json type of duration in `concurrency_control` to `u64` for pisa-proxy
=> fix(configs): fix serde json type of duration to u64 in pisa-proxy

charts/pisa-controller/crds/core.database-mesh.io_databaseendpoints.yaml, charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml, charts/pisa-controller/crds/core.database-mesh.io_virtualdatabases.yaml, pisa-controller/README.md, pisa-proxy/README.md
- add short name for CRD : DatabaseEndpoint -> dbep,TrafficStrategy -> ts,VirtualDatabase -> vdb
- add readme for pisa-controller && pisa-proxy
=> feat(readme，shortname): add short name for CRD,add readme

pisa-proxy/protocol/mysql/src/mysql_const.rs
1. refactor column_type and column_flag in `mysql_const`.
Currently, the column_type and column_flag definition cannot satisfy the future parsing column because their definition is ambiguous.
=> refactor(protocol): refactor column_type and column_flag in mysql const

pisa-proxy/Cargo.lock, pisa-proxy/protocol/codegen/Cargo.toml, pisa-proxy/protocol/codegen/etc/license.template, pisa-proxy/protocol/codegen/src/lib.rs, pisa-proxy/protocol/codegen/src/mysql_codec.rs, pisa-proxy/protocol/codegen/tests/tests.rs, pisa-proxy/protocol/mysql/Cargo.toml, pisa-proxy/protocol/mysql/src/client/codec.rs
1. refactor client codec convert for mysql client protocol.
Use procedural macro to reduce duplication of `ClientCodec`  convert.
=> Refactor(protocol):  refactor client codec convert for mysql client protocol

pisa-proxy/parser/mysql/src/lex.rs, pisa-proxy/parser/mysql/src/parser.rs
1.  fix `global` is None in ast when parsing  `set @@global.` statements
=> fix(parser): fix global is None in ast when parsing  statements

pisa-proxy/proxy/loadbalance/src/balance.rs, pisa-proxy/proxy/src/proxy.rs, pisa-proxy/runtime/mysql/src/server/server.rs, pisa-proxy/runtime/mysql/src/transaction_fsm.rs
- change loadbalance dynamic dispatch from dyn to enum
- add read write splitting config option
=> refactor(loadbalance):change loadbalance dynamic dispatch from dyn to enum

pisa-proxy/parser/mysql/src/lex.rs, pisa-proxy/parser/mysql/src/parser.rs
1. Fix parsing `identifer.identifer` failed when `.identifier` is keyword , like `select * from mysql.select`.
=> fix(parser): fix parsing `identifer.identifer` failed

pisa-proxy/proxy/strategy/src/config.rs
1. Changed type of `default_target` from `String` to `TargetRole`
=> feat(strategy): change type of default_target

charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml, pisa-controller/pkg/kubernetes/types.go, pisa-controller/pkg/proxy/config.go, pisa-controller/pkg/proxy/types.go, pisa-proxy/app/api/src/config.rs
Close #91 
- Add ReadWriteSplitting as LoadBalaning attribute in TrafficStrategy
- Update TrafficStrategy CRD
- Update `5591` as default admin port
=> feat(crd): update TrafficStrategy to support ReadWriteSplitting

pisa-proxy/protocol/mysql/src/client/auth.rs, pisa-proxy/protocol/mysql/src/client/conn.rs, pisa-proxy/protocol/mysql/src/server/conn.rs, pisa-proxy/proxy/pool/src/conn_pool.rs, pisa-proxy/proxy/strategy/src/readwritesplitting/rule_match.rs, pisa-proxy/proxy/strategy/src/readwritesplitting/static_rw.rs, pisa-proxy/proxy/strategy/src/route.rs, pisa-proxy/runtime/mysql/src/server/server.rs, pisa-proxy/runtime/mysql/src/transaction_fsm.rs
Close #132 
1.  Add  handling `set autocommit`, sql will force forward to readwrite backend when autocommit = 0 
2.  Add `autocommit` status for ConnAttr
=> fix(strategy):  Force forward readwrite backend when set autocommit=0

pisa-proxy/parser/mysql/src/lex.rs, pisa-proxy/parser/mysql/src/parser.rs
Close #139  
1. Fix parsing failed like statemet `select * from test.test limit 1`
2. Uncomment for statements  of unit test in the parser.
=> fix(parse): fix can't parse `select * from test.test limit 1`

pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/ast/mod.rs, pisa-proxy/parser/mysql/src/grammar.y, pisa-proxy/parser/mysql/src/parser.rs
Close #61 . 
- support show create view sql parser.
=> Feat(parser): support show create view sql parser.

pisa-controller/pkg/proxy/types.go
- rename serverVersion to server_version to fix Pisa-Proxy can't parse config from Pisa-Controller.
=> fix: rename serverVersion to server_version

pisa-proxy/protocol/mysql/src/util.rs
ref #160 
1. fix the packet whether is EOF Packet.
If packet is a `EOF` packet, the length of payload is <= 5 by the captured packets analyzed as follows:
```
05 00 00 2a fe 00 00 02 00
```
@dongzl
=> fix(protocol): fix the packet whether is EOF Packet

pisa-proxy/Cargo.lock, pisa-proxy/protocol/mysql/src/client/conn.rs, pisa-proxy/protocol/mysql/src/server/conn.rs, pisa-proxy/protocol/mysql/src/util.rs, pisa-proxy/proxy/pool/Cargo.toml, pisa-proxy/proxy/pool/src/conn_pool.rs, pisa-proxy/runtime/mysql/src/server/server.rs, pisa-proxy/runtime/mysql/src/transaction_fsm.rs
1. optimize get_conn for conn pool, use map instead of for loop
2. cargo fmt, remove unused imports
=> refactor(pool): optimize get_conn, use map instead of for loop

pisa-proxy/runtime/mysql/src/server/server.rs
- add reset transaction fsm after get set command
=> fix(runtime): add reset transaction fsm after get set names command

pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/ast/mod.rs, pisa-proxy/parser/mysql/src/grammar.y, pisa-proxy/parser/mysql/src/parser.rs
Signed-off-by: Zonglei Dong <dongzonglei@apache.org>
ref: #61 
- add show replica status sql parser.
https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy
```
TEXT_STRING_sys_nonewline:
TEXT_STRING_sys
{
if (!strcont($1.str, "\n"))
$$= $1;
else
{
my_error(ER_WRONG_VALUE, MYF(0), "argument contains not-allowed LF", $1.str);
MYSQL_YYABORT;
}
}
;
```
Rust implement:
```
TEXT_STRING_sys_nonewline -> String:
'TEXT_STRING'
{
String::from($lexer.span_str($1.as_ref().unwrap().span()))
}
;
```
=> Feat(parser): add show replica status sql parser.

pisa-controller/pkg/webhook/injection.go, pisa-proxy/Cargo.lock, pisa-proxy/app/config/Cargo.toml, pisa-proxy/app/config/src/config.rs, pisa-proxy/http/src/controllers/version.rs
Close #189 
- Add subcommand `daemon` to Pisa-Proxy, with arguments `config` for local config file
- Add subcommand `sidecar` to Pisa-Proxy, with arguments `pisa-controller-host` for the server address of Pisa-Controller, `pisa-deployed-namespace` for the namespace of target Pisa-Proxy, and `pisa-deployed-name` for the VirtualDatabase name of target Pisa-Proxy
- Add `args: ["sidecar"]` to sidecar container injected by Pisa-Controller
Side effects
- Env `LOCAL_CONFIG` is deprecated
=> feat(subcommand): add subcommand `sidecar` and `daemon` to Pisa-Proxy

pisa-proxy/protocol/mysql/src/client/codec.rs, pisa-proxy/protocol/mysql/src/client/conn.rs, pisa-proxy/protocol/mysql/src/column.rs, pisa-proxy/protocol/mysql/src/lib.rs, pisa-proxy/protocol/mysql/src/row.rs, pisa-proxy/protocol/mysql/src/util.rs
ref: #194 
1. Split `RowData` method
`RowData` struct changed to a Trait to support parsing  `Text Protocol ResultsetRow` and `Binary Protocol Resultset Row`.
Add `RowDataText` struct to support parsing  `Text Protocol ResultsetRow`.
2. Add `QuestResultStream` for easy used.
=> refactor parsing resultset row 

pisa-proxy/protocol/mysql/src/client/codec.rs, pisa-proxy/protocol/mysql/src/client/conn.rs, pisa-proxy/protocol/mysql/src/client/stream.rs, pisa-proxy/proxy/pool/src/conn_pool.rs, pisa-proxy/runtime/mysql/src/transaction_fsm.rs
1.  Add rebuild_conn method for broken conn in pool.
=> feat(pisa-proxy, runtime): add rebuild_conn for broken conn in pool.

pisa-controller/pkg/webhook/injection.go, pisa-controller/pkg/webhook/injection_test.go, pisa-controller/pkg/webhook/server.go, pisa-controller/pkg/webhook/types.go
=> refactor(webhook): refactor sidecar injection

pisa-proxy/Cargo.lock, pisa-proxy/Cargo.toml, pisa-proxy/audit/aws/Cargo.toml, pisa-proxy/audit/aws/src/aws.rs, pisa-proxy/audit/aws/src/lib.rs
- Add a workspace `audit/aws` for AWS CloudWatch
Further work needed.
=> feat(aws): init AWS CloudWatch

pisa-proxy/parser/mysql/src/ast/ddl.rs, pisa-proxy/parser/mysql/src/grammar.y, pisa-proxy/parser/mysql/src/parser.rs
ref #61  
- add create tablespace sql parser. 
- add create tablespace sql parser test case.
=> Feat(parser): add create tablespace sql parser. 

pisa-proxy/protocol/mysql/src/client/auth.rs, pisa-proxy/protocol/mysql/src/client/codec.rs, pisa-proxy/protocol/mysql/src/client/conn.rs, pisa-proxy/protocol/mysql/src/client/stream.rs, pisa-proxy/protocol/mysql/src/server/stream.rs
Add get_inner for local_stream to get underlying io. Also, this pr is optimized for the client's LocalStream.
=> feat(pisa-proxy, protocol): add get_inner for local_stream to get underlying io

pisa-proxy/protocol/mysql/src/server/auth.rs, pisa-proxy/protocol/mysql/src/server/codec.rs, pisa-proxy/protocol/mysql/src/server/mod.rs, pisa-proxy/protocol/mysql/src/server/stream.rs
1. Add packet codec. 
Used to reading packet from client side.
=> feat(pisa-proxy, protocol): add packet codec

pisa-proxy/parser/mysql/src/ast/dml.rs
1.  Fix incorrect when format PARTATION and LIMIT.
=> fix(pisa-proxy,parser): fix incorrect when format PARTATION and LIMIT

pisa-proxy/runtime/mysql/src/mysql.rs, pisa-proxy/runtime/mysql/src/server/server.rs
1. Remove 4 byte header when use PacketSend::Encode to send.
=> fix(pisa-proxy, protocol): remove 4 byte header when use PacketSend::Encode

pisa-proxy/protocol/mysql/src/client/auth.rs, pisa-proxy/protocol/mysql/src/client/codec.rs, pisa-proxy/protocol/mysql/src/server/auth.rs, pisa-proxy/protocol/mysql/src/server/codec.rs, pisa-proxy/protocol/mysql/src/util.rs
Add encode for ok packet, Also this pr fixed:
1. Fix put_lenc_int put 0xfb when `n` is num.
2. Fix other error for unit test of server codec
ref: #257
=> feat(pisa-proxy, protocol): add encode for ok packet

pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/grammar.y
To optimize ast struct For support sharding rewrite feature.
1. Add CTE struct
2. Add SubQuery struct
3. Remove is_paren, is_embd field in Query struct
ref: #257
=> feat(pisa-proxy, parser): optimzie query ast struct

pisa-proxy/parser/mysql/src/ast/base.rs, pisa-proxy/parser/mysql/src/ast/mod.rs
1. Fix format TableIdent and InExprs.
2. Add format method to `SqlStmt` enum.
=> fix(pisa-proxy, parser): fix format TableIdent and InExprs

pisa-proxy/parser/mysql/src/ast/dml.rs
1. Fix `PARTATION` format incorrect for `Insert` stmt.
=> fix(pisa-proxy, parser): fix `PARTITION` format incorrect for `Insert` stmt

pisa-proxy/parser/mysql/src/ast/api.rs, pisa-proxy/parser/mysql/src/ast/base.rs, pisa-proxy/parser/mysql/src/ast/mod.rs
1. Changed method trans return type to `&mut self `for `Transformer` trait to reduce clone.
=> Feat(pisa-proxy, parser): change method trans return type to &mut self for Transformer trait

.github/workflows/build.yml, .github/workflows/integration.yml
- Enable cache for Kaniko build action in both build and integration
- Set Kaniko cache_registry to `pisanixio/controller-cache` and `pisanixio/proxy-cache` respectively
=> chore(ci): add cache for kaniko

pisa-proxy/parser/mysql/src/ast/ddl.rs, pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/grammar.y, pisa-proxy/parser/mysql/src/lex.rs, pisa-proxy/parser/mysql/src/lib.rs
staement
1.  Fix parse failed which contains "a.*" in sql statement.
2.  Fix some typo error.
3.  Add `Span` field to struct `Item::Wild` .
4. Add `TableIdent` struct for get `Span` info.
=> fix(pisa-proxy, parser): Fix parse failed which contains "a.*" in sql statement

pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/grammar.y
1. Add `LimitOption` struct for get `Span` info.
=> feat(pisa-proxy, parser): add LimitOption struct for get Span info

pisa-proxy/parser/mysql/src/ast/api.rs, pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/ast/mod.rs
1. Add `complete` function to `Transformer` trait.
When visit to struct has completed, `complete` function called.
2. Update the return value of `trans`.   
Change the return value from `&mut self` to `bool`  for `trans` function means that whether continue visit ast struct.
=> feat(pisa-proxy, parser): Optimize Transformer trait, add `complete`

pisa-proxy/Cargo.lock, pisa-proxy/app/config/Cargo.toml, pisa-proxy/app/config/src/config.rs, pisa-proxy/app/server/src/server.rs, pisa-proxy/parser/mysql/src/ast/base.rs, pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/grammar.y, pisa-proxy/protocol/mysql/src/client/codec.rs, pisa-proxy/protocol/mysql/src/client/conn.rs, pisa-proxy/protocol/mysql/src/err.rs, pisa-proxy/proxy/endpoint/src/endpoint.rs, pisa-proxy/proxy/pool/src/conn_pool.rs, pisa-proxy/proxy/strategy/Cargo.toml, pisa-proxy/proxy/strategy/src/config.rs, pisa-proxy/proxy/strategy/src/readwritesplitting/dynamic_rw.rs, pisa-proxy/proxy/strategy/src/readwritesplitting/rule_match.rs, pisa-proxy/proxy/strategy/src/readwritesplitting/static_rw.rs, pisa-proxy/proxy/strategy/src/rewrite.rs, pisa-proxy/proxy/strategy/src/route.rs, pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs, pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs, pisa-proxy/runtime/mysql/Cargo.toml, pisa-proxy/runtime/mysql/src/mysql.rs, pisa-proxy/runtime/mysql/src/server/executor.rs, pisa-proxy/runtime/mysql/src/server/mod.rs, pisa-proxy/runtime/mysql/src/server/server.rs, pisa-proxy/runtime/mysql/src/server/stmt_cache.rs, pisa-proxy/runtime/mysql/src/transaction_fsm.rs
1. Add sharding feature.
ref: #257
=> Reat rewrite9

pisa-proxy/Cargo.lock, pisa-proxy/proxy/strategy/src/readwritesplitting/rule_match.rs, pisa-proxy/proxy/strategy/src/readwritesplitting/static_rw.rs, pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs, pisa-proxy/runtime/mysql/src/transaction_fsm.rs
- update sharding return value
=> chore(sharding): update sharding return value

pisa-proxy/protocol/mysql/src/lib.rs, pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs, pisa-proxy/runtime/mysql/Cargo.toml, pisa-proxy/runtime/mysql/src/server/executor.rs, pisa-proxy/runtime/mysql/src/server/server.rs, pisa-proxy/runtime/mysql/src/server/stmt_cache.rs, pisa-proxy/runtime/mysql/src/transaction_fsm.rs
1.  Add merge sort by sharding column.
2.  Fix unit test failed for fsm.
=> feat(pisa-proxy, sharding): Add merge sort by sharding column

pisa-proxy/app/config/src/config.rs, pisa-proxy/app/config/src/env_const.rs
- using `l` for short flag of `loglevel`
- update default value of admin host, port and loglevel to empty string
=> fix(proxy): update default value of admin host, port and loglevel to empty string

pisa-proxy/app/config/src/config.rs, pisa-proxy/cmd/pisa/src/main.rs
Close #317  
- Using `unwrap_or_default()` to handle invalid http request
- Checking config.proxy before build servers, if none, only start http server
=> fix(proxy): checking config.proxy before build servers

pisa-daemon/app/config/src/config.rs, pisa-daemon/app/traffic_qos/src/tc.rs, pisa-daemon/tc/src/tc.rs
1.  Add `Endpoint` field to `Service`.
2.  Changed `qos_group` type from Vec to Option.
3. Fix some unit test error.
=> feat(pisa-daemon, config): add `Endpoint` field to `Service`

pisa-controller/go.mod, pisa-controller/go.sum, pisa-controller/pkg/kubernetes/resources.go, pisa-controller/pkg/proxy/builder.go, pisa-controller/pkg/proxy/http.go, pisa-controller/pkg/proxy/http_test.go, pisa-controller/pkg/proxy/server.go
- Add handler for Pisa-Daemon config
- Add Pisa-Daemon config definition
- Add unit test for PisaDaemonConfigBuilder
=> feat(controller): add PisaDaemonConfig handler and builders

pisa-daemon/Cargo.lock, pisa-daemon/app/config/Cargo.toml, pisa-daemon/app/config/src/config.rs, pisa-daemon/app/config/src/env_const.rs, pisa-daemon/app/config/src/lib.rs
- Add PisaDaemonConfigBuilder as retrieve config from PisaController
- Introduce `clap` and `reqwest` to cargo
=> feat(pisa-daemon): add PisaDaemonConfigBuilder

pisa-daemon/bpf/tc/app.c
1.  Convert ip and port from network byte order to host byte order.
=> fix(pisa-daemon): fix byte order in bpf

pisa-proxy/parser/mysql/src/ast/dal.rs, pisa-proxy/parser/mysql/src/ast/mod.rs, pisa-proxy/parser/mysql/src/grammar.y, pisa-proxy/parser/mysql/src/parser.rs
Signed-off-by: Zonglei Dong <dongzonglei@apache.org>
ref #61  
- add create role sql parser.
- add create role sql parser test case.
=> Feat(parser): add create role sql parser.

.github/workflows/unit-test.yml, pisa-proxy/hack/Dockerfile
1. Fix docker build faield since use rust nightly version
2. Replace actions-rs/toolchain with dtolnay/rust-toolchain. see [link](https://github.com/actions-rs/toolchain/issues/216).
=> fix(build): fix docker build faield since use rust nightly version

pisa-proxy/parser/mysql/src/ast/api.rs, pisa-proxy/parser/mysql/src/ast/base.rs, pisa-proxy/parser/mysql/src/ast/dml.rs, pisa-proxy/parser/mysql/src/ast/mod.rs, pisa-proxy/parser/mysql/src/ast/tcl.rs
1. Optimize ast visitor for parser to avoid  unneed `clone` method.
=> optimize(parser): Optimize ast visitor, remove clone method

pisa-proxy/protocol/mysql/src/util.rs
according to MySQL source code `sql/auth/sha2_password.cc caching_sha2_password_authenticate`, empty password should be set to '\0'
modify calc_caching_sha2password code to correctly handle empty password
when database has empty password, current calc_caching_sha2password cannot handle it correctly. we should set to vec![0] instead of vec![]
=> fix : we should set password to vec[0] when password is empty in Client Auth Plugin: caching_sha2_password

pisa-proxy/examples/example-config.toml, pisa-proxy/plugin/src/circuit_break/mod.rs, pisa-proxy/plugin/src/config.rs, pisa-proxy/plugin/src/tests/mod.rs
it is friendly to provide case_insensitive option to `proxy.config.plugin.circuit_break` 
```
[[proxy.config.plugin.circuit_break]]
regex = ["111", "^SELECT .* FOR UPDATE"]
case_insensitive = true
```
Tests 
- Unit test(done)
=> feat(CircuitBreak regex case_insensitive match config)
