docs/docs/Features/loadbalancer.md
docs/docs/Features/mysql-protocol.md

update loadbalancer.md & mysql-protocol.md

update: update loadbalancer & mysql protocol document

---

CONTRIBUTING.md
pisa-proxy/runtime/mysql/src/server/server.rs

- Fix duration metrics
- Add contribution guide

fix duration metrics and add contribution guide

---

pisa-proxy/hack/Dockerfile

- Fix path to `target/debug/pisa-proxy` in Dockerfile

fix: path in pisa-proxy dockerfile

---

pisa-controller/hack/Dockerfile

- rename `pisa-controller` to `controller` under bin

fix: binary artifact of pisa-controller

---

pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/parser/mysql/src/ast/mod.rs
pisa-proxy/parser/mysql/src/grammar.y
pisa-proxy/parser/mysql/src/parser.rs

- support parsing deallocate prepare. 
- add visit impl
https://dev.mysql.com/doc/refman/8.0/en/deallocate-prepare.html

parser: support deallocate prepare

---

charts/pisa-controller/templates/deployment.yaml
charts/pisa-controller/templates/service.yaml

1.  Fix helm args and port name for new flag

FIX: Fix helm args and port name for new flag

---

pisa-proxy/protocol/mysql/src/client/conn.rs
pisa-proxy/proxy/pool/src/conn_pool.rs
pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

1. Fix get conn error in fsm.
2. Add `get_db` method for `ConnAttr`.

Fix(runtime): fix get conn error in fsm

---

pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/parser/mysql/src/lex.rs
pisa-proxy/protocol/mysql/src/client/conn.rs
pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

- fix(runtime): add handle_query execute fsm trigger
- format code

fix(runtime): add handle_query execute fsm trigger

---

pisa-controller/pkg/proxy/config.go
pisa-controller/pkg/proxy/types.go

- fix json tag for MySQL port
- fix sprintf format of proxy port

fix(configs): fix port format and json definition of pisa-controller

---

pisa-controller/pkg/proxy/types.go

- fix simple loadbalance json tag of nodes of pisa-controller

fix(configs): fix simple loadbalance json tag of nodes of pisa-controller

---

example/config-sample.yaml
pisa-controller/pkg/proxy/config.go

-  fix sample to fit new CRD  username -> user, port string -> int32
- add default admin.port

Fix(sample): fix sample to fit new CRD ,Add(configs): add default port 

---

pisa-proxy/examples/example-config.toml
pisa-proxy/proxy/src/proxy.rs
pisa-proxy/runtime/mysql/src/server/server.rs

- fix init db handler return value packet
- format code

fix(runtime): fix handle init db reture value

---

.github/workflows/rust.yml

- using `--release` for pisa-proxy cargo build

fix(ci): using release for cargo build

---

pisa-controller/README.md
pisa-controller/hack/Dockerfile
pisa-proxy/hack/Dockerfile

Close #xxx 
- add multi-stage docker build  for pisa-controller && pisa-proxy
- build binary file in one Dockerfile

chore(Dockerfile): add multi-stage docker build 

---

pisa-controller/hack/Dockerfile

- change docker file to fit Makefile

chore(Dockerfile): change docker file to fit Makefile

---

.github/workflows/ci.yml

- fix ci variable name tag -> tags

fix(ci): fix ci variable name 

---

pisa-controller/Makefile

1.  Update Makefile to add git info for build

chore(pisa-controller): Update Makefile to add git info for build

---

.github/workflows/build.yml

- add a new ci file for build image on push master
- to fix problem https://github.community/t/github-actions-cannot-read-personal-access-key-from-secrets/123852

feat(build image): new ci for build docker image on push master && release

---

pisa-proxy/Cargo.lock
pisa-proxy/runtime/common/Cargo.toml
pisa-proxy/runtime/common/src/ast_cache.rs
pisa-proxy/runtime/mysql/src/mysql.rs
pisa-proxy/runtime/mysql/src/server/mod.rs

1. For prevent memory growth, used lru cache instand of hashmap for ast cache.

feat(runtime): add  lru for ast cache

---

.github/workflows/ci.yml

- add Golang unit test for Pisa-Controller
- add Rust unit test for Pisa-Proxy

chore(ci): add unit test for golang and rust

---

pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/parser/mysql/src/ast/mod.rs
pisa-proxy/parser/mysql/src/grammar.y
pisa-proxy/parser/mysql/src/parser.rs

For #61 
parser:support parse show tables
https://dev.mysql.com/doc/refman/8.0/en/show-tables.html

parser:support parse show tables

---

pisa-proxy/protocol/mysql/src/client/codec.rs
pisa-proxy/proxy/pool/src/conn_pool.rs

1. fix failure to run unit tests for codec
2. change to private function for `get_conn` and `put_conn` in `PoolInner`

fix(protocol): fix failure to run unit tests for codec

---

pisa-proxy/protocol/mysql/src/client/column.rs
pisa-proxy/protocol/mysql/src/client/mod.rs
pisa-proxy/protocol/mysql/src/client/resultset.rs
pisa-proxy/protocol/mysql/src/util.rs

1. support parse column.
2. remove unused code in util.

feat(protocol): support parse column

---

docs/docs/UseCases/standalone.md

- Add standalone deployment steps

docs: add standalone deployment steps

---

pisa-proxy/parser/mysql/src/ast/api.rs
pisa-proxy/parser/mysql/src/ast/base.rs
pisa-proxy/parser/mysql/src/ast/etc/license.template
pisa-proxy/parser/mysql/src/ast/mod.rs
pisa-proxy/parser/mysql/src/ast/tcl.rs
pisa-proxy/parser/mysql/src/grammar.y
pisa-proxy/parser/mysql/src/parser.rs

Close #93  
1. Support TCL statements parseing.

Feat(parser): support TCL statements parsing

---

pisa-proxy/Cargo.lock
pisa-proxy/examples/example-config.toml
pisa-proxy/proxy/strategy/src/config.rs

- update read write splitting config

update(strategy): update read write splitting config

---

pisa-proxy/Makefile
pisa-proxy/protocol/mysql/src/mysql_const.rs

Close #102  
1. Fix typo in mysql_const
2. Fix shell output color not turned off

fix(protocol): fix typo in mysql_const, fix shell  output color for Makefile

---

pisa-proxy/Cargo.lock
pisa-proxy/Cargo.toml
pisa-proxy/app/api/src/config.rs
pisa-proxy/app/config/src/config.rs
pisa-proxy/app/metrics/src/metrics.rs
pisa-proxy/app/server/Cargo.toml
pisa-proxy/app/server/src/backend_const.rs
pisa-proxy/app/server/src/server.rs
pisa-proxy/cmd/pisa/src/main.rs
pisa-proxy/http/src/http.rs
pisa-proxy/proxy/src/factory.rs
pisa-proxy/runtime/shardingsphereproxy/Cargo.toml
pisa-proxy/runtime/shardingsphereproxy/src/lib.rs
pisa-proxy/runtime/shardingsphereproxy/src/shardingsphereproxy.rs

- using `HttpServerFactory` for httpserver
- rename any shardingproxy to shardingsphereproxy

refactor(server): using factory for httpserver

---

docs/docs/intro.md
docs/i18n/en/docusaurus-plugin-content-docs/current/intro.md
pisa-controller/pkg/proxy/config.go

Close #68 
- Add default host as `0.0.0.0` and port `3306` to  default MySQL type VirtualDatabase
- Update community info in docs

fix(crd): add default host and port to MySQL type VirtualDatabase

---

pisa-proxy/parser/mysql/src/ast/dml.rs

fix(parser): fix typo `BOLLEAN` in dml.rs

---

charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml
pisa-controller/pkg/kubernetes/types.go
pisa-controller/pkg/proxy/types.go

- Using regex array for CircuitBreak, ConcurrencyControl and ReadWriteSplitting in TrafficStrategy

refactor(config): using regex array in TrafficStrategy

---

docs/docs/Features/readwritesplitting.md
docs/docs/Features/sql-circuit-breaker-and-concurrency-control.md
docs/docs/Features/sql-parser.md
docs/docs/UseCases/kubernetes.md

1. add readwritesplitting doc
2. update kubernetes.md, sql-circuit*.md for `regex`.

Feat(docs): update docs for readwritesplitting

---

docs/docs/UseCases/kubernetes.md

1. add VirtualDatabase use notes

chore(docs): add VirtualDatabase CRD use notes

---

.github/workflows/integration.yml
charts/pisa-controller/templates/deployment.yaml
docs/docs/Features/readwritesplitting.md
pisa-controller/pkg/kubernetes/client.go
pisa-controller/pkg/proxy/config.go
pisa-controller/pkg/proxy/types.go
pisa-controller/pkg/webhook/injection.go
test/kubernetes/app.yml

1. Add debug flag for helm install in integration test  workflow.
2. Fix get role attr value of DatabaseEndpoit is empty.
3. Fix kube client cannot use `RestInClusterConfig` mode  when `homedir` exists.
4. Fix patch json unmarshal failed for webhook.
5. Add `omitempty` tag for  Plugin field of Proxy  config.
6. Adjust resource order for app.yaml in test/kubernetes.

fix(pisa-controller): fix pisa-controller integration test failed

---

charts/pisa-controller/Chart.yaml
charts/pisa-controller/values.yaml

Close #xxx 
- Update version from `v0.1.0` to `v0.1.1` in Charts

chore(helm): update charts version

---

docs/docs/Features/readwritesplitting.md

1. update comments in readwritesplitting example config

chore(docs): update comments in readwritesplitting example config

---

.github/workflows/integration.yml

Signed-off-by: windghoul <windghoul@gmail.com>
Close #141 
- fix it get imagetag is null

fix(it): fix it get imagetag is null

---

pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/parser/mysql/src/ast/mod.rs
pisa-proxy/parser/mysql/src/grammar.y
pisa-proxy/parser/mysql/src/parser.rs

ref: #61 .
- Support show columns from table SQL parser.

Feat(parser): Support show columns from table SQL parser.

---

pisa-proxy/protocol/mysql/src/server/conn.rs
pisa-proxy/protocol/mysql/src/server/packet.rs
pisa-proxy/runtime/mysql/src/server/server.rs

- optimize Pisa-Proxy runtime Error return

chore(runtime): change runtime ProtocolError to pisa error

---

pisa-proxy/protocol/mysql/src/client/auth.rs
pisa-proxy/protocol/mysql/src/client/codec.rs
pisa-proxy/protocol/mysql/src/client/conn.rs
pisa-proxy/protocol/mysql/src/server/conn.rs
pisa-proxy/proxy/pool/src/conn_pool.rs
pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

1. Refactor init_session_attr for fsm.
Add ConnAttrMut for change  session attr.
3. Fix unit test failed in codec.

refactor(runtime, protocol): refactor init_session_attr for fsm

---

pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

Close #145  
1. Fix get endpoint failed when execute some `set` statement.

Fix(runtime): fix get endpoint failed when execute some `set` statement

---

.github/workflows/build.yml

- Build `Pisa-Controller` and `Pisa-Proxy` when push a new tag

chore(ci): update build workflow with tag condition

---

pisa-proxy/parser/mysql/src/lex.rs
pisa-proxy/parser/mysql/src/parser.rs
pisa-proxy/protocol/mysql/src/client/conn.rs
pisa-proxy/runtime/mysql/src/server/server.rs

Close #147 
- add get_conn error handler

chore(runtime): add get_conn error handler

---

docs/docs/UseCases/kubernetes.md
pisa-proxy/protocol/mysql/src/charset.rs

1. update comments for charset.
2. fix `role` description in doc.

chore(docs,  protocol): update role description in docs and comments for charset

---

.github/workflows/check-license.yml

Signed-off-by: windghoul <windghoul@gmail.com>
- fix ci ckecklicense not found docker file

fix(ci): fix ci check-license not found docker file

---

README.md
docs/docs/intro.md
docs/i18n/en/docusaurus-plugin-content-docs/current/intro.md
docs/versioned_docs/version-v0.1.0/intro.md
docs/versioned_docs/version-v0.1.1/intro.md

- Fix dev meeting for English start point to 16th Feb.

fix(docs): fix dev meetings schedule

---

pisa-proxy/app/config/src/config.rs
pisa-proxy/app/server/src/server.rs
pisa-proxy/cmd/pisa/src/main.rs
pisa-proxy/http/src/controllers/version.rs
pisa-proxy/http/src/http.rs
pisa-proxy/proxy/src/proxy.rs

- Rename PisaConfig to PisaProxyConfig and remove ProtocolConfig, aka Config
- Fix version in PisaProxyConfig
- Introduce builder

refactor(config): refactor PisaProxyConfig

---

pisa-proxy/app/config/src/config.rs
pisa-proxy/app/server/src/server.rs
pisa-proxy/cmd/pisa/src/main.rs
pisa-proxy/http/src/controllers/version.rs
pisa-proxy/runtime/mysql/src/server/server.rs

- Remove unused `mut` decorator
- Using private member for PisaProxyConfig
- Remove unused embedded member like Admin, MySQL, and Proxy, which cause some variable like log_level unset before

fix(config): fix common config unset issue

---

pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/parser/mysql/src/ast/mod.rs
pisa-proxy/parser/mysql/src/grammar.y
pisa-proxy/parser/mysql/src/parser.rs

ref #61 
- Feat(parser): add show grants sql parser.

Feat(parser): add show grants sql parser. 

---

pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/protocol/mysql/src/client/auth.rs
pisa-proxy/proxy/loadbalance/src/balance.rs
pisa-proxy/proxy/loadbalance/src/random_weighted.rs
pisa-proxy/proxy/loadbalance/src/roundrobin_weighted.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/static_rw.rs
pisa-proxy/proxy/strategy/src/route.rs

- change lb `next` method return value with ownership

refactor(loadbalance): change lb next method return Endpoint with ownership

---

.github/workflows/code-coverage.yml

Close #191 
Add golang code coverage and integrate Codecov.

ci: golang code coverage and integrate Codecov

---

pisa-proxy/runtime/mysql/src/transaction_fsm.rs

For #149
- Unit test
- add test for transaction_fsm

runtime:mysql:transaction_fsm: add test for transaction_fsm

---

pisa-proxy/app/config/src/config.rs
pisa-proxy/app/config/src/env_const.rs
pisa-proxy/app/config/src/lib.rs
pisa-proxy/cmd/pisa/src/main.rs

Close #xxx 
- Move all env const to a separate file
- Rename `load_config()` to `build()`, `build_from_cmd()` to `collect_from_cmd()`
- Simplify `build()` procedure
- Add basic test for `build_from_http()` and `build_from_file()`

refctor(config): Simplify config

---

pisa-proxy/protocol/mysql/src/client/codec.rs
pisa-proxy/protocol/mysql/src/client/conn.rs
pisa-proxy/protocol/mysql/src/column.rs
pisa-proxy/protocol/mysql/src/lib.rs
pisa-proxy/protocol/mysql/src/macros.rs
pisa-proxy/protocol/mysql/src/row.rs
pisa-proxy/protocol/mysql/src/util.rs

feat: add macros.rs

---

example/config-sample.yaml

Signed-off-by: windghoul <windghoul@gmail.com>
- fix example yaml , regex string to slice

fix(example): fix example regex string to slice

---

charts/pisa-controller/crds/core.database-mesh.io_trafficstrategies.yaml
pisa-controller/pkg/kubernetes/types.go
pisa-controller/pkg/proxy/builder.go
pisa-controller/pkg/proxy/builder_test.go
pisa-controller/pkg/proxy/types.go

- Add support of ReadWriteSplitting Dynamic Discovery MasterHighAvailability

feat(config): add config support for dynamic readwrite splitting

---

pisa-proxy/proxy/endpoint/src/endpoint.rs
pisa-proxy/proxy/strategy/src/config.rs
pisa-proxy/proxy/strategy/src/discovery/monitor_reconcile.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/dynamic_rw.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/mod.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/rule_match.rs

- optimize rules match dispatch

chore(strategy): optimize rules match dispatch

---

pisa-proxy/proxy/strategy/src/discovery/monitor_reconcile.rs
pisa-proxy/proxy/strategy/src/monitors/connect_monitor.rs
pisa-proxy/proxy/strategy/src/monitors/ping_monitor.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/dynamic_rw.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

1. Remove unessary clone.
2. Remove unused import.

chore(pisa-proxy, strategy): remove unessary clone, remove unused import

---

charts/pisa-controller/Chart.yaml
charts/pisa-controller/values.yaml

- update version from v0.1.1 to v0.2.0

chore(charts): update version from v0.1.1 to v0.2.0

---

pisa-proxy/proxy/strategy/src/monitors/replication_lag_monitor.rs

- update read only check in replication lag monitor

chore(strategy): update read only check in replication lag monitor

---

pisa-controller/cmd/pisa-controller/http/http.go
pisa-controller/cmd/pisa-controller/webhook/webhook.go

fix: fix tls in webhook

---

pisa-proxy/proxy/strategy/src/monitors/connect_monitor.rs
pisa-proxy/proxy/strategy/src/monitors/ping_monitor.rs
pisa-proxy/proxy/strategy/src/monitors/read_only_monitor.rs

fix(strategy): fix retries reset

---

docs/docs/Features/readwritesplitting.md
docs/versioned_docs/version-v0.2.0/Features/readwritesplitting.md

fix(docs): fix kubernetes config

---

pisa-controller/go.mod
pisa-controller/pkg/proxy/builder.go
pisa-controller/pkg/proxy/builder_test.go
pisa-controller/pkg/proxy/types.go

test(config): add test for proxy config

---

pisa-controller/pkg/proxy/builder.go
pisa-controller/pkg/proxy/builder_test.go
pisa-controller/pkg/proxy/http.go
pisa-controller/pkg/proxy/http_test.go
pisa-controller/pkg/proxy/types.go

- Add test for PisaProxyConfig

test(config): add test for PisaProxyConfig

---

pisa-proxy/protocol/mysql/src/client/codec.rs
pisa-proxy/proxy/strategy/src/discovery/monitor_reconcile.rs
pisa-proxy/proxy/strategy/src/monitors/ping_monitor.rs
pisa-proxy/proxy/strategy/src/monitors/replication_lag_monitor.rs
pisa-proxy/runtime/mysql/src/mysql.rs
pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

Close #131 
- fix issue #131. When all of the backend are failed,Pisa-Proxy will refused connect.

fix(runtime): add accept connect check.

---

README.md

fix(docs): fix readme links

---

README.md

- Fix release badges in README.md

fix(docs): fix badge in readme

---

pisa-controller/pkg/webhook/injection.go
pisa-controller/pkg/webhook/injection_test.go
pisa-controller/pkg/webhook/types.go

test(injection): add unit test

---

pisa-controller/pkg/webhook/injection.go
pisa-controller/pkg/webhook/injection_test.go
pisa-controller/pkg/webhook/types.go

- Using a `PisaControllerInjectionMeta` and `PisaProxyINjectionMeta` for injection 
- Using json marshal for patch rendering

refactor(injection): using a typed struct for injection

---

pisa-proxy/parser/mysql/src/lex.rs

1. Use simd to implement the to_upper function, If cpu has `sse2` feature, will be enabled  simd to_upper.
When `sql ident` is sample, this pr has the same performance.
When `sql ident` is complex, the `sql ident` length is grater then 16, the performance will be improved  by about 5%.
simd:
```bash
running 1 test
test tests::bench_simd_parser ... bench:       3,593 ns/iter (+/- 216)
```
no_simd:
```
running 1 test
test tests::bench_parser ... bench:       3,834 ns/iter (+/- 228)
```

feat(pisa-proxy, parser): add simd to upper char in lex.rs

---

pisa-controller/go.mod
pisa-controller/go.sum
pisa-controller/pkg/kubernetes/resources.go
pisa-controller/pkg/proxy/types.go
pisa-controller/pkg/webhook/injection.go
pisa-controller/pkg/webhook/server.go

What is changed and how it works?
Close #227 
Related changes
- support genric type in static rules
- fix injection err handle
- skip health check log

feat(config): support genric type in static rules

---

pisa-controller/pkg/proxy/builder_test.go
pisa-controller/pkg/proxy/http.go
pisa-controller/pkg/proxy/http_test.go

fix(controller): fix unit test dependency and dbeplist

---

pisa-proxy/parser/mysql/src/lex.rs

fix(lexer): using a general macro for m1 target

---

pisa-proxy/protocol/mysql/src/server/mod.rs

1. fix typo in mod.rs, codec_handhsake rename to auth

fix(pisa-proxy, protocol): fix typo in mod.rs

---

pisa-proxy/proxy/strategy/src/config.rs
pisa-proxy/proxy/strategy/src/discovery/discovery.rs
pisa-proxy/proxy/strategy/src/discovery/monitor_reconcile.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/dynamic_rw.rs

Close #226
support dynamic monitor switch

discovery: support dynamic monitor switch

---

pisa-proxy/protocol/mysql/src/server/auth.rs

fix(pisa-proxy, protocol): fix license typo

---

pisa-proxy/proxy/src/proxy.rs
pisa-proxy/proxy/strategy/src/config.rs

Close #269 
- add shard config

feat(sharding): add sharding config

---

pisa-proxy/runtime/mysql/src/server/server.rs

1. Fix encode fieldlist response packet error.

fix(pisa-proxy,protocol): fix encode fieldlist response packet error

---

pisa-proxy/protocol/mysql/src/client/codec.rs
pisa-proxy/protocol/mysql/src/common_packet.rs
pisa-proxy/protocol/mysql/src/lib.rs
pisa-proxy/protocol/mysql/src/row.rs

1. Split ResultOkInfo to common_packet .

Feat(pisa-proxy, protocol): Split ResultOkInfo to common_packet 

---

pisa-proxy/parser/mysql/build.rs
pisa-proxy/parser/mysql/src/ast/base.rs
pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/parser/mysql/src/ast/mod.rs

1. Optimize Visit method, Reduce clone method calls

Optimize(pisa-proxy, parser):  Reduce clone method calls

---

pisa-controller/pkg/webhook/types.go

chore(webhook): remove commented codes

---

pisa-proxy/parser/mysql/src/ast/api.rs
pisa-proxy/parser/mysql/src/ast/base.rs
pisa-proxy/parser/mysql/src/grammar.y

1.  Add ast struct for aggregate function

feat(pisa-proxy, parser): add ast struct for aggregate function

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

- add table strategy sql rewrote

feat(sharding): add table strategy sql rewrite

---

pisa-proxy/proxy/strategy/src/readwritesplitting/rule_match.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/static_rw.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

1.  Add rewrite for insert statment. 
2. Fix unit test failed for `readwritesplitting`.

Feat(pisa-proxy, sharding): add insert statement rewrite

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

1. Add sharding-column to `ShardingRewriteOutput`

feat(pisa-proxy): add sharding-column to `RewriteOutput`

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

1. Add `ShardingMeta` trait.
2. Remove duplicate code.

Optimize(pisa-proxy, sharding): optimize sharding_rewrite

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/generic_meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

1. Add generic_meta.rs for pr #311 .

fix(pisa-proxy, sharding): add generic_meta.rs

---

pisa-proxy/parser/mysql/src/ast/base.rs
pisa-proxy/parser/mysql/src/ast/mod.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

Close #xxx 
1. Fix run delete and update statement faild in sharding mode.
2. Fix unit test for sql ast

fix(pisa-proxy, shardind): fix run delete and update statement faild in sharding mode

---

pisa-proxy/Cargo.lock
pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

- add `AVG` sql rewrite
- fix test case error

feat(sharding): add avg sql rewrite

---

pisa-proxy/protocol/mysql/src/client/codec.rs
pisa-proxy/proxy/strategy/src/rewrite.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs
pisa-proxy/runtime/mysql/src/server/executor.rs
pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

1.  Add support use `use db` statement.
2.  Add `buf` limit in MergeStream.

feat(pisa-proxy, sharding): support  use db, optimize MergeStream

---

docs/docs/UseCases/kubernetes.md

Update kubernetes demo instruction

docs: update kubernetes demo instruction

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/rewrite_const.rs

- add order by & group by sql rewrite

feat(sharding): add order by & group by sql rewrite

---

pisa-proxy/runtime/mysql/src/server/executor.rs

chore(sharding): optimize sharding sort

---

pisa-proxy/protocol/mysql/src/client/codec.rs
pisa-proxy/protocol/mysql/src/row.rs
pisa-proxy/runtime/mysql/src/mysql.rs
pisa-proxy/runtime/mysql/src/server/executor.rs
pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/server/stmt_cache.rs

1. Fix prepare execute failed in the sharding mode.
2. Update MergeStream, when `data` is None, will don't push.

Fix(pisa-proxy, sharding): fix prepare execute failed in the sharding mode

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs
pisa-proxy/runtime/mysql/src/server/executor.rs

Signed-off-by: wbtlb <wangbo@sphere-ex.com>
-  optimize order group by sql rewrite

chore(sharding): optimize order group by sql rewrite

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

- add sharding order group change meta

feat(sharding): add sharding order group change meta

---

pisa-controller/pkg/proxy/builder.go

Close #xxx 
- Seperator DataShard and TrafficStrategy while building PisaProxyConfig

fix(builder): make datashard and trafficstrategy seperate

---

charts/pisa-controller/crds/core.database-mesh.io_datashards.yaml
charts/pisa-controller/crds/core.database-mesh.io_virtualdatabases.yaml
pisa-controller/go.mod
pisa-controller/go.sum
pisa-controller/pkg/kubernetes/resources.go
pisa-controller/pkg/proxy/builder.go
pisa-controller/pkg/proxy/http.go

- Add DataShard reference to VirtualDatabase
- Introduce crd of DataShard
- Fix DataShard build in PisaProxyConfig builder

fix(controller): fix DataShard filter and build

---

.gitignore
charts/pisa-controller/values.yaml
docs/docs/UseCases/kubernetes.md

- Update default version both in values.yaml and documents to v0.3.0
- Update .gitignore with ignoring Helm compressed file .tgz

chore(deploy): update default version to v0.3.0

---

pisa-controller/pkg/proxy/builder_test.go
pisa-controller/pkg/proxy/http_test.go

- Fix unit test for HttpBuilder

fix(controller): fix unit test

---

pisa-proxy/proxy/strategy/src/readwritesplitting/dynamic_rw.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/rule_match.rs
pisa-proxy/proxy/strategy/src/readwritesplitting/static_rw.rs
pisa-proxy/proxy/strategy/src/route.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs
pisa-proxy/runtime/mysql/src/mysql.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

1.  Fix sql execute failed when in sharding and rw mode.
2.  Remove comments code.

fix(pisa-proxy, sharding): fix sql execute failed when in sharding and rw mode

---

charts/pisa-controller/crds/core.database-mesh.io_datashards.yaml
charts/pisa-controller/crds/core.database-mesh.io_virtualdatabases.yaml
example/sharding/app.yml
example/sharding/databaseendpoint.yml
example/sharding/datashard.yml
example/sharding/mysql.yml
example/sharding/run.sh
example/sharding/trafficstrategy.yml
example/sharding/virtualdatabase.yml
pisa-controller/pkg/proxy/builder.go
pisa-proxy/runtime/mysql/src/mysql.rs

Close #xxx 
- Add sharding example
- Fix license header
- Remove `omitempty` tag to NodeGroup.member

fix(config): remove omitempty tag to NodeGroup.member

---

docs/docs/Features/sharding.md
docs/docs/UseCases/kubernetes.md

Signed-off-by: wbtlb <wangbo@sphere-ex.com>
- update sharding docs

chore(docs): update sharding docs

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs

Signed-off-by: wbtlb <wangbo@sphere-ex.com>
- add DeleteStmt
- remove unuse code

chore(sharding): add DeleteStmt

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs
pisa-proxy/runtime/mysql/src/server/executor.rs

Signed-off-by: wbtlb <wangbo@sphere-ex.com>
- update database strategy

feat(sharding): update database strategy

---

pisa-proxy/parser/mysql/src/ast/dml.rs

1. Add check is_skip for visit Items.

Feat(pisa-proxy, parser): Add check is_skip for visit Items 

---

pisa-controller/pkg/proxy/builder_test.go
pisa-proxy/parser/mysql/src/ast/base.rs
pisa-proxy/parser/mysql/src/grammar.y

- unify base operation definition with upper case

chore(parser): unify base operation definition with upper case

---

pisa-controller/go.mod
pisa-controller/go.sum
pisa-controller/pkg/kubernetes/resources.go
pisa-controller/pkg/proxy/builder.go
pisa-controller/pkg/proxy/http.go
pisa-controller/pkg/proxy/http_test.go
pisa-controller/pkg/proxy/server.go

- Using `/daemonconfigs` for DaemonConfig
- Add PodContainerBinding for DaemonConfig
- Update CRD type definition

feat(controller): update daemon config definition

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

- database strategy add avg sql rewrite
- database strategy add order by sql rewrite
- database strategy add group by sql rewrite

feat(sharding): add sql rewrite in database strategy

---

pisa-proxy/parser/mysql/src/ast/base.rs
pisa-proxy/parser/mysql/src/ast/dml.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

1.  Add get min, max function in meta.
2. Fix avg_field incorrect when avg contains `alias_name`.
3. Fix duplicate rewrite_outputs. 
4. Fix unit test failed.

feat(pisa-proxy, sharding): add get min, max function in meta

---

docs/docs/Features/sharding.md
docs/docs/UseCases/standalone.md

feat(doc): update database strategy docs

---

docs/docs/Features/sharding.md

- add crd config in sharding doc

feat(sharding): add crd docs

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

1. Optimize sharding_rewrite to reduce code.

Optimize(pisa-proxy, rewrite): optimize sharding_rewrite to reduce code.

---

pisa-controller/pkg/proxy/builder.go

1.  Fix panic when TableStrategy is nil.

fix(pisa-controller): fix panic when TableStrategy is nil

---

pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs

- fix database table strategy rewrite error
- fix insert get value error

fix(sharding): fix database table strategy rewrite error

---

pisa-proxy/protocol/mysql/src/row.rs
pisa-proxy/runtime/mysql/src/server/executor.rs

- fix min max error
- remove comment

fix(sharding): fix min max error

---

pisa-proxy/protocol/mysql/src/macros.rs
pisa-proxy/protocol/mysql/src/row.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/meta.rs
pisa-proxy/proxy/strategy/src/sharding_rewrite/mod.rs
pisa-proxy/runtime/mysql/Cargo.toml
pisa-proxy/runtime/mysql/src/server/executor.rs

This PR also has changes as follows:
1. Using `lexical` parse string to float64 in chunk to fix parse i64 failed.
2. Added update_columns for RowData trait.
3. Optimized crc32mod.

refactor(runtime): refactor get_avg meta, and refactor handle_avg in executor

---

pisa-controller/go.mod
pisa-controller/go.sum
pisa-controller/pkg/controllers/database_chaos.go
pisa-controller/pkg/controllers/virtualdatabase.go

Close #xxx 
- Support AWS RDS Cluster in VirtualDatabase
- Support AWS RDS Cluster in DatabaseChaos

feat: support AWS RDS Cluster in VirtualDatabase and DatabaseChaos

---

pisa-controller/cmd/pisa-controller/controller-manager/manager.go
pisa-controller/go.mod
pisa-controller/go.sum
pisa-controller/pkg/aws/rds.go
pisa-controller/pkg/controllers/database_chaos.go
pisa-controller/pkg/controllers/virtualdatabase.go

Close #xxx 
- Update golang-sdk
- Introduce AWS client

refactor(controller): introduce AWS rds client to VirtualDatabase and DatabaseChaos controller

---

pisa-proxy/http/src/http.rs
pisa-proxy/version/Cargo.toml
pisa-proxy/version/src/version.rs

1. Add `vergen` to build dependencies to fix GIT_BRANCH, GIT_COMMIT is empty.

fix(version): add vergen to build dependencies

---

pisa-proxy/Cargo.lock
pisa-proxy/protocol/mysql/Cargo.toml
pisa-proxy/protocol/mysql/src/value.rs
pisa-proxy/runtime/mysql/Cargo.toml
pisa-proxy/runtime/mysql/src/server/executor.rs
pisa-proxy/version/src/version.rs

1. Fix cargo build warning 
2. Update Cargo.lock
3. `openssl` crate add `vendored features` for `mysql protocol`  to reduce dependency on dynamic library.

chore(runtime,protocol): fix cargo warning, update cargo.lock and openssl dependency

---

pisa-proxy/version/build.rs

1. Add build.rs, related pr #405

fix(version): add build.rs

---

pisa-proxy/protocol/mysql/src/client/conn.rs
pisa-proxy/proxy/pool/Cargo.toml
pisa-proxy/proxy/pool/src/conn_pool.rs
pisa-proxy/runtime/mysql/src/server/executor.rs
pisa-proxy/runtime/mysql/src/server/server.rs
pisa-proxy/runtime/mysql/src/transaction_fsm.rs

1. Add retry for get_conn in conn_pool.
2. Add timeout wrapper for Handshake in client protocol.

feat(pool): add retry for get_conn

---

pisa-proxy/protocol/mysql/src/client/resultset.rs

1. `resultset codec`  renew method optimization, remove `take` auth_info to avoid memory read.

Optimize(protocol): optimize resultset codec  renew

---

pisa-controller/go.mod
pisa-controller/go.sum
pisa-controller/pkg/controllers/database_endpoint.go
pisa-controller/pkg/controllers/virtualdatabase.go

Close #xxx 
- PR to update `pisanix/docs/cn`:
- PR to update `pisanix/protocol`:
- Need to cherry-pick to the release branch
Tests 
- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code
Side effects
- Performance regression
- Consumes more CPU
- Consumes more MEM
- Breaking backward compatibility
```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

feat: update rds cluster and aurora creation

---

pisa-controller/pkg/controllers/database_endpoint.go
pisa-controller/pkg/controllers/virtualdatabase.go

Close #xxx 
- PR to update `pisanix/docs/cn`:
- PR to update `pisanix/protocol`:
- Need to cherry-pick to the release branch
Tests 
- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code
Side effects
- Performance regression
- Consumes more CPU
- Consumes more MEM
- Breaking backward compatibility
```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

fix: fix AWS Rds cluster and aurora deletion
